export const items = [
  {
    itemName: "Футбол / Спартак",
    playerName: "Eskekel Ponce",
    statusBuy: "Buy",
    statusConf: "Confirmed",
    price: "price",
    quantity: "1",
    from: "Nullanddress",
    to: "Josie",
    time: "3 HOURS AGO",
  },
  {
    itemName: "Футбол / Спартак",
    playerName: "PAblo Ponce",
    statusBuy: "Buy",
    statusConf: "waiting",
    price: "price",
    quantity: "1",
    from: "Nullanddress",
    to: "Josie",
    time: "3 HOURS AGO",
  },
  {
    itemName: "Футбол / Спартак",
    playerName: "Danil Ponce",
    statusBuy: "Buy",
    statusConf: "waiting",
    price: "price",
    quantity: "1",
    from: "Nullanddress",
    to: "Josie",
    time: "3 HOURS AGO",
  },
  {
    itemName: "Футбол / Спартак",
    playerName: "Eskekel Ponce",
    statusBuy: "Buy",
    statusConf: "Confirmed",
    price: "price",
    quantity: "1",
    from: "Nullanddress",
    to: "Josie",
    time: "3 HOURS AGO",
  },
  {
    itemName: "Футбол / Спартак",
    playerName: "Eskekel Ponce",
    statusBuy: "Buy",
    statusConf: "Confirmed",
    price: "price",
    quantity: "1",
    from: "Nullanddress",
    to: "Josie",
    time: "3 HOURS AGO",
  },
  {
    itemName: "Футбол / Спартак",
    playerName: "Eskekel Ponce",
    statusBuy: "Buy",
    statusConf: "Confirmed",
    price: "price",
    quantity: "1",
    from: "Nullanddress",
    to: "Josie",
    time: "3 HOURS AGO",
  },
]
