import imageUrl from "../../images/marketplace/offerCards/players/Christian_Andrade_common.webp"

export const data = [
  {
    id: 1,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 2,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 3,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 33,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 4,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 5,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 6,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 7,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 8,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 9,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 10,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 11,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 12,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 13,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 14,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 15,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
  {
    id: 16,
    brickColor: "#3985f5",
    text: "soccer",
    playerName: "Christian Andrade",
    usdValue: "100",
    imageUrl: imageUrl,
    cryptoValue: "100 YLT",
    speed: 50,
    dexterity: 40,
    stamina: 30,
    dribbling: 50,
    finishing: 50,
    status: "not listed",
    allNFT: true,
  },
]
